name = "Efus"
uuid = "285369d7-3617-4bce-982e-acda657aee64"
authors = ["ken-morel <engonken@gmail.com>"]
version = "0.1.0"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"

[compat]
FunctionWrappers = "1.1.3"
ParserCombinator = "2.2.1"
