name = "Efus"
uuid = "285369d7-3617-4bce-982e-acda657aee64"
authors = ["ken-morel <engonken@gmail.com>"]
version = "0.1.0"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"

[compat]
FunctionWrappers = "1.1.3"
