name = "Efus"
uuid = "9109e250-8bcb-41d8-9faa-e136e3e06a79"
authors = ["Engon Ken Morel <engonken8@gmail.com> and contributors"]
version = "0.1.0"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
FunctionWrappers = "1.1.3"
MacroTools = "0.5.16"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
