/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON = 3,
  anon_sym_DOT_DOT_DOT = 4,
  anon_sym_if = 5,
  anon_sym_end = 6,
  anon_sym_elseif = 7,
  anon_sym_else = 8,
  anon_sym_for = 9,
  anon_sym_LPAREN = 10,
  aux_sym_julia_block_token1 = 11,
  anon_sym_RPAREN = 12,
  anon_sym_COMMA = 13,
  anon_sym_COLON_COLON = 14,
  sym_string_literal = 15,
  sym_number_literal = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_julia_expression = 19,
  sym_julia_expression_in_value = 20,
  sym_comment = 21,
  sym__indent = 22,
  sym__dedent = 23,
  sym__newline = 24,
  sym_source_file = 25,
  sym__statement = 26,
  sym__identifier_statement = 27,
  sym_component_call = 28,
  sym_property_assignment = 29,
  sym_grouped_property_assignment = 30,
  sym_splat_operator = 31,
  sym_if_statement = 32,
  sym_else_if_clause = 33,
  sym_else_clause = 34,
  sym_for_statement = 35,
  sym_julia_block = 36,
  sym_snippet_definition = 37,
  sym__parameters = 38,
  sym_parameter = 39,
  sym__value = 40,
  sym_boolean_literal = 41,
  sym__block = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_component_call_repeat1 = 44,
  aux_sym_if_statement_repeat1 = 45,
  aux_sym_julia_block_repeat1 = 46,
  aux_sym_julia_block_repeat2 = 47,
  aux_sym__parameters_repeat1 = 48,
  aux_sym__block_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_if] = "if",
  [anon_sym_end] = "end",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_LPAREN] = "(",
  [aux_sym_julia_block_token1] = "julia_block_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON_COLON] = "::",
  [sym_string_literal] = "string_literal",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_julia_expression] = "julia_expression",
  [sym_julia_expression_in_value] = "julia_expression_in_value",
  [sym_comment] = "comment",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__identifier_statement] = "_identifier_statement",
  [sym_component_call] = "component_call",
  [sym_property_assignment] = "property_assignment",
  [sym_grouped_property_assignment] = "grouped_property_assignment",
  [sym_splat_operator] = "splat_operator",
  [sym_if_statement] = "if_statement",
  [sym_else_if_clause] = "else_if_clause",
  [sym_else_clause] = "else_clause",
  [sym_for_statement] = "for_statement",
  [sym_julia_block] = "julia_block",
  [sym_snippet_definition] = "snippet_definition",
  [sym__parameters] = "_parameters",
  [sym_parameter] = "parameter",
  [sym__value] = "_value",
  [sym_boolean_literal] = "boolean_literal",
  [sym__block] = "_block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_component_call_repeat1] = "component_call_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_julia_block_repeat1] = "julia_block_repeat1",
  [aux_sym_julia_block_repeat2] = "julia_block_repeat2",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym__block_repeat1] = "_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_julia_block_token1] = aux_sym_julia_block_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_string_literal] = sym_string_literal,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_julia_expression] = sym_julia_expression,
  [sym_julia_expression_in_value] = sym_julia_expression_in_value,
  [sym_comment] = sym_comment,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__identifier_statement] = sym__identifier_statement,
  [sym_component_call] = sym_component_call,
  [sym_property_assignment] = sym_property_assignment,
  [sym_grouped_property_assignment] = sym_grouped_property_assignment,
  [sym_splat_operator] = sym_splat_operator,
  [sym_if_statement] = sym_if_statement,
  [sym_else_if_clause] = sym_else_if_clause,
  [sym_else_clause] = sym_else_clause,
  [sym_for_statement] = sym_for_statement,
  [sym_julia_block] = sym_julia_block,
  [sym_snippet_definition] = sym_snippet_definition,
  [sym__parameters] = sym__parameters,
  [sym_parameter] = sym_parameter,
  [sym__value] = sym__value,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym__block] = sym__block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_component_call_repeat1] = aux_sym_component_call_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_julia_block_repeat1] = aux_sym_julia_block_repeat1,
  [aux_sym_julia_block_repeat2] = aux_sym_julia_block_repeat2,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym__block_repeat1] = aux_sym__block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_julia_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_julia_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_julia_expression_in_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_component_call] = {
    .visible = true,
    .named = true,
  },
  [sym_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_splat_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_if_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_else_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_julia_block] = {
    .visible = true,
    .named = true,
  },
  [sym_snippet_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_julia_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_julia_block_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_code = 1,
  field_condition = 2,
  field_default = 3,
  field_group = 4,
  field_iterator = 5,
  field_key = 6,
  field_name = 7,
  field_type = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_code] = "code",
  [field_condition] = "condition",
  [field_default] = "default",
  [field_group] = "group",
  [field_iterator] = "iterator",
  [field_key] = "key",
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 3},
  [9] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_code, 1},
  [2] =
    {field_condition, 1},
  [3] =
    {field_iterator, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_default, 2},
    {field_name, 0},
  [8] =
    {field_name, 0},
    {field_type, 2},
  [10] =
    {field_group, 0},
    {field_key, 2},
    {field_value, 4},
  [13] =
    {field_default, 4},
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 27,
  [30] = 24,
  [31] = 27,
  [32] = 24,
  [33] = 27,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 43,
  [49] = 44,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 39,
  [62] = 44,
  [63] = 43,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 43,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 45,
  [76] = 76,
  [77] = 46,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 44,
  [93] = 93,
  [94] = 94,
  [95] = 95,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 2,
        '#', 37,
        '(', 15,
        ')', 20,
        ',', 21,
        '.', 8,
        ':', 13,
        '=', 11,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(22);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_julia_block_token1);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '(' ||
          lookahead == ')') ADVANCE(37);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_julia_block_token1);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_julia_block_token1);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_julia_expression);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_julia_expression);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_julia_expression_in_value);
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '(') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_julia_expression_in_value);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ' ||
          lookahead == ')' ||
          lookahead == ',') ADVANCE(2);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_julia_expression_in_value);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == ')' ||
          lookahead == ',') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_julia_expression_in_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0, .external_lex_state = 4},
  [14] = {.lex_state = 0, .external_lex_state = 4},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0, .external_lex_state = 4},
  [40] = {.lex_state = 0, .external_lex_state = 4},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0, .external_lex_state = 4},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 4},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 0, .external_lex_state = 4},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 0, .external_lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0, .external_lex_state = 5},
  [65] = {.lex_state = 0, .external_lex_state = 5},
  [66] = {.lex_state = 0, .external_lex_state = 5},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(80),
    [sym__statement] = STATE(67),
    [sym__identifier_statement] = STATE(67),
    [sym_component_call] = STATE(67),
    [sym_if_statement] = STATE(67),
    [sym_for_statement] = STATE(67),
    [sym_julia_block] = STATE(67),
    [sym_snippet_definition] = STATE(67),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(22), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym__newline,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(67), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [34] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      sym__newline,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(67), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [68] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym__dedent,
    STATE(5), 1,
      aux_sym__block_repeat1,
    STATE(86), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [99] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      sym__dedent,
    STATE(6), 1,
      aux_sym__block_repeat1,
    STATE(86), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [130] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(48), 1,
      anon_sym_for,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      sym__dedent,
    STATE(6), 1,
      aux_sym__block_repeat1,
    STATE(86), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [161] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym__dedent,
    STATE(8), 1,
      aux_sym__block_repeat1,
    STATE(86), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [192] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      sym__dedent,
    STATE(6), 1,
      aux_sym__block_repeat1,
    STATE(86), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [223] = 5,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(64), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(60), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression_in_value,
  [245] = 5,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(64), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(42), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(68), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression_in_value,
  [267] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(70), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression_in_value,
  [289] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(60), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(76), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression_in_value,
  [311] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      sym__indent,
    ACTIONS(84), 1,
      sym__newline,
    STATE(78), 1,
      sym__block,
    STATE(14), 4,
      sym_property_assignment,
      sym_grouped_property_assignment,
      sym_splat_operator,
      aux_sym_component_call_repeat1,
  [336] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      sym__indent,
    ACTIONS(86), 1,
      sym__newline,
    STATE(82), 1,
      sym__block,
    STATE(15), 4,
      sym_property_assignment,
      sym_grouped_property_assignment,
      sym_splat_operator,
      aux_sym_component_call_repeat1,
  [358] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(91), 2,
      sym__indent,
      sym__newline,
    STATE(15), 4,
      sym_property_assignment,
      sym_grouped_property_assignment,
      sym_splat_operator,
      aux_sym_component_call_repeat1,
  [375] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_end,
    ACTIONS(95), 1,
      anon_sym_elseif,
    ACTIONS(97), 1,
      anon_sym_else,
    STATE(88), 1,
      sym_else_clause,
    STATE(18), 2,
      sym_else_if_clause,
      aux_sym_if_statement_repeat1,
  [395] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    ACTIONS(99), 3,
      anon_sym_if,
      anon_sym_for,
      sym_identifier,
  [409] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_elseif,
    ACTIONS(97), 1,
      anon_sym_else,
    ACTIONS(101), 1,
      anon_sym_end,
    STATE(91), 1,
      sym_else_clause,
    STATE(21), 2,
      sym_else_if_clause,
      aux_sym_if_statement_repeat1,
  [429] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      aux_sym_julia_block_token1,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    STATE(20), 2,
      sym_julia_block,
      aux_sym_julia_block_repeat1,
  [446] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      aux_sym_julia_block_token1,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(22), 2,
      sym_julia_block,
      aux_sym_julia_block_repeat1,
  [463] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_end,
    ACTIONS(115), 1,
      anon_sym_elseif,
    ACTIONS(118), 1,
      anon_sym_else,
    STATE(21), 2,
      sym_else_if_clause,
      aux_sym_if_statement_repeat1,
  [480] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      aux_sym_julia_block_token1,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(22), 2,
      sym_julia_block,
      aux_sym_julia_block_repeat1,
  [497] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 2,
      sym__dedent,
      anon_sym_LPAREN,
    ACTIONS(128), 3,
      anon_sym_if,
      anon_sym_for,
      sym_identifier,
  [510] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      aux_sym_julia_block_token1,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_julia_block_repeat2,
  [526] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(136), 1,
      aux_sym_julia_block_token1,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      aux_sym_julia_block_repeat2,
  [542] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_EQ,
    ACTIONS(144), 1,
      anon_sym_COLON_COLON,
    ACTIONS(142), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [556] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 1,
      aux_sym_julia_block_token1,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_julia_block_repeat2,
  [572] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_parameter,
    STATE(83), 1,
      sym__parameters,
  [588] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 1,
      aux_sym_julia_block_token1,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_julia_block_repeat2,
  [604] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      aux_sym_julia_block_token1,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      aux_sym_julia_block_repeat2,
  [620] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 1,
      aux_sym_julia_block_token1,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_julia_block_repeat2,
  [636] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      aux_sym_julia_block_token1,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_julia_block_repeat2,
  [652] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 1,
      aux_sym_julia_block_token1,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_julia_block_repeat2,
  [668] = 5,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      aux_sym_julia_block_token1,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_julia_block_repeat2,
  [684] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(178), 1,
      anon_sym_COLON,
    ACTIONS(180), 1,
      anon_sym_DOT_DOT_DOT,
  [697] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym__parameters_repeat1,
  [710] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym__parameters_repeat1,
  [723] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_EQ,
    ACTIONS(193), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [734] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 3,
      sym__indent,
      sym__newline,
      sym_identifier,
  [743] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      sym__indent,
      sym__newline,
      sym_identifier,
  [752] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_else,
    ACTIONS(199), 2,
      anon_sym_end,
      anon_sym_elseif,
  [763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 3,
      sym__indent,
      sym__newline,
      sym_identifier,
  [772] = 2,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(205), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [781] = 2,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(207), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [790] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_else,
    ACTIONS(209), 2,
      anon_sym_end,
      anon_sym_elseif,
  [801] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_else,
    ACTIONS(213), 2,
      anon_sym_end,
      anon_sym_elseif,
  [812] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_end,
    ACTIONS(219), 1,
      anon_sym_else,
    STATE(70), 1,
      sym_else_clause,
  [825] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 3,
      sym__indent,
      sym__newline,
      sym_identifier,
  [834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 3,
      sym__indent,
      sym__newline,
      sym_identifier,
  [843] = 2,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(174), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [852] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 3,
      sym__indent,
      sym__newline,
      sym_identifier,
  [861] = 2,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(227), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [870] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym__parameters_repeat1,
  [883] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_identifier,
    STATE(56), 1,
      sym_parameter,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [909] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__indent,
    STATE(69), 1,
      sym__block,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__indent,
    STATE(41), 1,
      sym__block,
  [929] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__indent,
    STATE(16), 1,
      sym__block,
  [939] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [947] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [971] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__indent,
    STATE(47), 1,
      sym__block,
  [981] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__indent,
    STATE(79), 1,
      sym__block,
  [991] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__indent,
    STATE(89), 1,
      sym__block,
  [1001] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym__newline,
  [1008] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym__newline,
  [1015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_end,
  [1022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_end,
  [1029] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym__newline,
  [1036] = 2,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_julia_expression,
  [1043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identifier,
  [1050] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym__newline,
  [1057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym__newline,
  [1064] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym__newline,
  [1071] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__newline,
  [1078] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__newline,
  [1085] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_end,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_identifier,
  [1106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym__newline,
  [1113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
  [1120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym__newline,
  [1127] = 2,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_julia_expression,
  [1134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym__newline,
  [1141] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_EQ,
  [1148] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_end,
  [1155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_end,
  [1162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym__newline,
  [1169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_end,
  [1176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym__newline,
  [1183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym__newline,
  [1190] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym__newline,
  [1197] = 2,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_julia_expression,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 161,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 223,
  [SMALL_STATE(10)] = 245,
  [SMALL_STATE(11)] = 267,
  [SMALL_STATE(12)] = 289,
  [SMALL_STATE(13)] = 311,
  [SMALL_STATE(14)] = 336,
  [SMALL_STATE(15)] = 358,
  [SMALL_STATE(16)] = 375,
  [SMALL_STATE(17)] = 395,
  [SMALL_STATE(18)] = 409,
  [SMALL_STATE(19)] = 429,
  [SMALL_STATE(20)] = 446,
  [SMALL_STATE(21)] = 463,
  [SMALL_STATE(22)] = 480,
  [SMALL_STATE(23)] = 497,
  [SMALL_STATE(24)] = 510,
  [SMALL_STATE(25)] = 526,
  [SMALL_STATE(26)] = 542,
  [SMALL_STATE(27)] = 556,
  [SMALL_STATE(28)] = 572,
  [SMALL_STATE(29)] = 588,
  [SMALL_STATE(30)] = 604,
  [SMALL_STATE(31)] = 620,
  [SMALL_STATE(32)] = 636,
  [SMALL_STATE(33)] = 652,
  [SMALL_STATE(34)] = 668,
  [SMALL_STATE(35)] = 684,
  [SMALL_STATE(36)] = 697,
  [SMALL_STATE(37)] = 710,
  [SMALL_STATE(38)] = 723,
  [SMALL_STATE(39)] = 734,
  [SMALL_STATE(40)] = 743,
  [SMALL_STATE(41)] = 752,
  [SMALL_STATE(42)] = 763,
  [SMALL_STATE(43)] = 772,
  [SMALL_STATE(44)] = 781,
  [SMALL_STATE(45)] = 790,
  [SMALL_STATE(46)] = 801,
  [SMALL_STATE(47)] = 812,
  [SMALL_STATE(48)] = 825,
  [SMALL_STATE(49)] = 834,
  [SMALL_STATE(50)] = 843,
  [SMALL_STATE(51)] = 852,
  [SMALL_STATE(52)] = 861,
  [SMALL_STATE(53)] = 870,
  [SMALL_STATE(54)] = 883,
  [SMALL_STATE(55)] = 893,
  [SMALL_STATE(56)] = 901,
  [SMALL_STATE(57)] = 909,
  [SMALL_STATE(58)] = 919,
  [SMALL_STATE(59)] = 929,
  [SMALL_STATE(60)] = 939,
  [SMALL_STATE(61)] = 947,
  [SMALL_STATE(62)] = 955,
  [SMALL_STATE(63)] = 963,
  [SMALL_STATE(64)] = 971,
  [SMALL_STATE(65)] = 981,
  [SMALL_STATE(66)] = 991,
  [SMALL_STATE(67)] = 1001,
  [SMALL_STATE(68)] = 1008,
  [SMALL_STATE(69)] = 1015,
  [SMALL_STATE(70)] = 1022,
  [SMALL_STATE(71)] = 1029,
  [SMALL_STATE(72)] = 1036,
  [SMALL_STATE(73)] = 1043,
  [SMALL_STATE(74)] = 1050,
  [SMALL_STATE(75)] = 1057,
  [SMALL_STATE(76)] = 1064,
  [SMALL_STATE(77)] = 1071,
  [SMALL_STATE(78)] = 1078,
  [SMALL_STATE(79)] = 1085,
  [SMALL_STATE(80)] = 1092,
  [SMALL_STATE(81)] = 1099,
  [SMALL_STATE(82)] = 1106,
  [SMALL_STATE(83)] = 1113,
  [SMALL_STATE(84)] = 1120,
  [SMALL_STATE(85)] = 1127,
  [SMALL_STATE(86)] = 1134,
  [SMALL_STATE(87)] = 1141,
  [SMALL_STATE(88)] = 1148,
  [SMALL_STATE(89)] = 1155,
  [SMALL_STATE(90)] = 1162,
  [SMALL_STATE(91)] = 1169,
  [SMALL_STATE(92)] = 1176,
  [SMALL_STATE(93)] = 1183,
  [SMALL_STATE(94)] = 1190,
  [SMALL_STATE(95)] = 1197,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_call, 1, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_call, 2, 0, 1),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_call_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_call_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 2, 0, 0), SHIFT_REPEAT(19),
  [171] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 2, 0, 0), SHIFT_REPEAT(34),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 7),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_assignment, 3, 0, 5),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_if_clause, 3, 0, 3),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_if_clause, 3, 0, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_property_assignment, 5, 0, 8),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_julia_block, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_julia_block, 3, 0, 2),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_julia_block, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_julia_block, 3, 0, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_splat_operator, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 3, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 6),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 5, 0, 9),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 4, 0, 4),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_definition, 6, 0, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [255] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_call, 3, 0, 1),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_clause, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 3),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 5, 0, 4),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_definition, 5, 0, 1),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
  },
  [3] = {
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__newline] = true,
  },
  [5] = {
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_efus_external_scanner_create(void);
void tree_sitter_efus_external_scanner_destroy(void *);
bool tree_sitter_efus_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_efus_external_scanner_serialize(void *, char *);
void tree_sitter_efus_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_efus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_efus_external_scanner_create,
      tree_sitter_efus_external_scanner_destroy,
      tree_sitter_efus_external_scanner_scan,
      tree_sitter_efus_external_scanner_serialize,
      tree_sitter_efus_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "efus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
