/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON = 3,
  anon_sym_DOT_DOT_DOT = 4,
  anon_sym_if = 5,
  anon_sym_end = 6,
  anon_sym_elseif = 7,
  anon_sym_else = 8,
  anon_sym_for = 9,
  anon_sym_LPAREN = 10,
  aux_sym_julia_block_token1 = 11,
  anon_sym_RPAREN = 12,
  anon_sym_COMMA = 13,
  anon_sym_COLON_COLON = 14,
  sym_string_literal = 15,
  sym_number_literal = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_julia_expression = 19,
  sym_comment = 20,
  sym__indent = 21,
  sym__dedent = 22,
  sym__newline = 23,
  sym_source_file = 24,
  sym__statement = 25,
  sym__identifier_statement = 26,
  sym_component_call = 27,
  sym_property_assignment = 28,
  sym_grouped_property_assignment = 29,
  sym_splat_operator = 30,
  sym_if_statement = 31,
  sym_else_if_clause = 32,
  sym_else_clause = 33,
  sym_for_statement = 34,
  sym_julia_block = 35,
  sym_snippet_definition = 36,
  sym__parameters = 37,
  sym_parameter = 38,
  sym__value = 39,
  sym_boolean_literal = 40,
  sym__block = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_component_call_repeat1 = 43,
  aux_sym_if_statement_repeat1 = 44,
  aux_sym_julia_block_repeat1 = 45,
  aux_sym_julia_block_repeat2 = 46,
  aux_sym__parameters_repeat1 = 47,
  aux_sym__block_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_if] = "if",
  [anon_sym_end] = "end",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_LPAREN] = "(",
  [aux_sym_julia_block_token1] = "julia_block_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON_COLON] = "::",
  [sym_string_literal] = "string_literal",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_julia_expression] = "julia_expression",
  [sym_comment] = "comment",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__identifier_statement] = "_identifier_statement",
  [sym_component_call] = "component_call",
  [sym_property_assignment] = "property_assignment",
  [sym_grouped_property_assignment] = "grouped_property_assignment",
  [sym_splat_operator] = "splat_operator",
  [sym_if_statement] = "if_statement",
  [sym_else_if_clause] = "else_if_clause",
  [sym_else_clause] = "else_clause",
  [sym_for_statement] = "for_statement",
  [sym_julia_block] = "julia_block",
  [sym_snippet_definition] = "snippet_definition",
  [sym__parameters] = "_parameters",
  [sym_parameter] = "parameter",
  [sym__value] = "_value",
  [sym_boolean_literal] = "boolean_literal",
  [sym__block] = "_block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_component_call_repeat1] = "component_call_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_julia_block_repeat1] = "julia_block_repeat1",
  [aux_sym_julia_block_repeat2] = "julia_block_repeat2",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym__block_repeat1] = "_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_julia_block_token1] = aux_sym_julia_block_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_string_literal] = sym_string_literal,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_julia_expression] = sym_julia_expression,
  [sym_comment] = sym_comment,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__identifier_statement] = sym__identifier_statement,
  [sym_component_call] = sym_component_call,
  [sym_property_assignment] = sym_property_assignment,
  [sym_grouped_property_assignment] = sym_grouped_property_assignment,
  [sym_splat_operator] = sym_splat_operator,
  [sym_if_statement] = sym_if_statement,
  [sym_else_if_clause] = sym_else_if_clause,
  [sym_else_clause] = sym_else_clause,
  [sym_for_statement] = sym_for_statement,
  [sym_julia_block] = sym_julia_block,
  [sym_snippet_definition] = sym_snippet_definition,
  [sym__parameters] = sym__parameters,
  [sym_parameter] = sym_parameter,
  [sym__value] = sym__value,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym__block] = sym__block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_component_call_repeat1] = aux_sym_component_call_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_julia_block_repeat1] = aux_sym_julia_block_repeat1,
  [aux_sym_julia_block_repeat2] = aux_sym_julia_block_repeat2,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym__block_repeat1] = aux_sym__block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_julia_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_julia_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__identifier_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_component_call] = {
    .visible = true,
    .named = true,
  },
  [sym_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_splat_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_if_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_else_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_julia_block] = {
    .visible = true,
    .named = true,
  },
  [sym_snippet_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_julia_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_julia_block_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_code = 1,
  field_condition = 2,
  field_default = 3,
  field_group = 4,
  field_iterator = 5,
  field_key = 6,
  field_name = 7,
  field_type = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_code] = "code",
  [field_condition] = "condition",
  [field_default] = "default",
  [field_group] = "group",
  [field_iterator] = "iterator",
  [field_key] = "key",
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 3},
  [9] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_code, 1},
  [2] =
    {field_condition, 1},
  [3] =
    {field_iterator, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_default, 2},
    {field_name, 0},
  [8] =
    {field_name, 0},
    {field_type, 2},
  [10] =
    {field_group, 0},
    {field_key, 2},
    {field_value, 4},
  [13] =
    {field_default, 4},
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 23,
  [28] = 24,
  [29] = 23,
  [30] = 24,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 41,
  [56] = 42,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 48,
  [62] = 41,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 1,
        '#', 35,
        '(', 15,
        ')', 20,
        ',', 21,
        '.', 8,
        ':', 13,
        '=', 11,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(22);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_julia_block_token1);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '(' ||
          lookahead == ')') ADVANCE(35);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_julia_block_token1);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_julia_block_token1);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_julia_expression);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_julia_expression);
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_julia_expression);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_julia_expression);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0, .external_lex_state = 2},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 4},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 5},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(70),
    [sym__statement] = STATE(74),
    [sym__identifier_statement] = STATE(74),
    [sym_component_call] = STATE(74),
    [sym_if_statement] = STATE(74),
    [sym_for_statement] = STATE(74),
    [sym_julia_block] = STATE(74),
    [sym_snippet_definition] = STATE(74),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(22), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym__newline,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(74), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [34] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      sym__newline,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(74), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [68] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      sym__dedent,
    STATE(6), 1,
      aux_sym__block_repeat1,
    STATE(82), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [99] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      sym__dedent,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(82), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [130] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(48), 1,
      anon_sym_for,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      sym__dedent,
    STATE(6), 1,
      aux_sym__block_repeat1,
    STATE(82), 7,
      sym__statement,
      sym__identifier_statement,
      sym_component_call,
      sym_if_statement,
      sym_for_statement,
      sym_julia_block,
      sym_snippet_definition,
  [161] = 5,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(56), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression,
  [183] = 5,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(64), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression,
  [205] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(66), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression,
  [227] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(59), 3,
      sym_julia_block,
      sym__value,
      sym_boolean_literal,
    ACTIONS(72), 4,
      sym_string_literal,
      sym_number_literal,
      sym_identifier,
      sym_julia_expression,
  [249] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      sym__newline,
    STATE(13), 4,
      sym_property_assignment,
      sym_grouped_property_assignment,
      sym_splat_operator,
      aux_sym_component_call_repeat1,
  [268] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_end,
    ACTIONS(82), 1,
      anon_sym_elseif,
    ACTIONS(84), 1,
      anon_sym_else,
    STATE(77), 1,
      sym_else_clause,
    STATE(15), 2,
      sym_else_if_clause,
      aux_sym_if_statement_repeat1,
  [288] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(86), 1,
      sym__newline,
    STATE(16), 4,
      sym_property_assignment,
      sym_grouped_property_assignment,
      sym_splat_operator,
      aux_sym_component_call_repeat1,
  [304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    ACTIONS(88), 3,
      anon_sym_if,
      anon_sym_for,
      sym_identifier,
  [318] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_elseif,
    ACTIONS(84), 1,
      anon_sym_else,
    ACTIONS(90), 1,
      anon_sym_end,
    STATE(76), 1,
      sym_else_clause,
    STATE(21), 2,
      sym_else_if_clause,
      aux_sym_if_statement_repeat1,
  [338] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym__newline,
    STATE(16), 4,
      sym_property_assignment,
      sym_grouped_property_assignment,
      sym_splat_operator,
      aux_sym_component_call_repeat1,
  [354] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      aux_sym_julia_block_token1,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(18), 2,
      sym_julia_block,
      aux_sym_julia_block_repeat1,
  [371] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      aux_sym_julia_block_token1,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    STATE(19), 2,
      sym_julia_block,
      aux_sym_julia_block_repeat1,
  [388] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    ACTIONS(110), 1,
      aux_sym_julia_block_token1,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    STATE(19), 2,
      sym_julia_block,
      aux_sym_julia_block_repeat1,
  [405] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 2,
      sym__dedent,
      anon_sym_LPAREN,
    ACTIONS(115), 3,
      anon_sym_if,
      anon_sym_for,
      sym_identifier,
  [418] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_end,
    ACTIONS(119), 1,
      anon_sym_elseif,
    ACTIONS(122), 1,
      anon_sym_else,
    STATE(21), 2,
      sym_else_if_clause,
      aux_sym_if_statement_repeat1,
  [435] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      sym_identifier,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_parameter,
    STATE(83), 1,
      sym__parameters,
  [451] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 1,
      aux_sym_julia_block_token1,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_julia_block_repeat2,
  [467] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      aux_sym_julia_block_token1,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_julia_block_repeat2,
  [483] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      aux_sym_julia_block_token1,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_julia_block_repeat2,
  [499] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_EQ,
    ACTIONS(150), 1,
      anon_sym_COLON_COLON,
    ACTIONS(148), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [513] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      aux_sym_julia_block_token1,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_julia_block_repeat2,
  [529] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      aux_sym_julia_block_token1,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_julia_block_repeat2,
  [545] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(158), 1,
      aux_sym_julia_block_token1,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_julia_block_repeat2,
  [561] = 5,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      aux_sym_julia_block_token1,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_julia_block_repeat2,
  [577] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_else,
    ACTIONS(164), 2,
      anon_sym_end,
      anon_sym_elseif,
  [588] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_EQ,
    ACTIONS(170), 1,
      anon_sym_COLON,
    ACTIONS(172), 1,
      anon_sym_DOT_DOT_DOT,
  [601] = 2,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(174), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [610] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym__parameters_repeat1,
  [623] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_else,
    ACTIONS(180), 2,
      anon_sym_end,
      anon_sym_elseif,
  [634] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_end,
    ACTIONS(186), 1,
      anon_sym_else,
    STATE(72), 1,
      sym_else_clause,
  [647] = 2,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(144), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_EQ,
    ACTIONS(190), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [667] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym__parameters_repeat1,
  [680] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_else,
    ACTIONS(197), 2,
      anon_sym_end,
      anon_sym_elseif,
  [691] = 2,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(201), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [700] = 2,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(203), 3,
      anon_sym_LPAREN,
      aux_sym_julia_block_token1,
      anon_sym_RPAREN,
  [709] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym__parameters_repeat1,
  [722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      sym__newline,
      sym_identifier,
  [730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym__newline,
    STATE(63), 1,
      sym__block,
  [748] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      sym_identifier,
    STATE(54), 1,
      sym_parameter,
  [758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      sym__newline,
      sym_identifier,
  [766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      sym__newline,
      sym_identifier,
  [774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym__newline,
    STATE(69), 1,
      sym__block,
  [784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym__newline,
    STATE(40), 1,
      sym__block,
  [794] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [802] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym__newline,
    STATE(36), 1,
      sym__block,
  [812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 2,
      sym__newline,
      sym_identifier,
  [828] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 2,
      sym__newline,
      sym_identifier,
  [836] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym__newline,
    STATE(84), 1,
      sym__block,
  [846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      sym__newline,
      sym_identifier,
  [854] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [862] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym__newline,
    STATE(12), 1,
      sym__block,
  [872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_end,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_identifier,
  [902] = 2,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_julia_expression,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym__newline,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__newline,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_EQ,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_end,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym__newline,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_end,
  [958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym__newline,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym__newline,
  [972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym__newline,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_end,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_end,
  [993] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym__newline,
  [1000] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym__indent,
  [1007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym__newline,
  [1014] = 2,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_julia_expression,
  [1021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym__newline,
  [1028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
  [1035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_end,
  [1042] = 2,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym_julia_expression,
  [1049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 161,
  [SMALL_STATE(8)] = 183,
  [SMALL_STATE(9)] = 205,
  [SMALL_STATE(10)] = 227,
  [SMALL_STATE(11)] = 249,
  [SMALL_STATE(12)] = 268,
  [SMALL_STATE(13)] = 288,
  [SMALL_STATE(14)] = 304,
  [SMALL_STATE(15)] = 318,
  [SMALL_STATE(16)] = 338,
  [SMALL_STATE(17)] = 354,
  [SMALL_STATE(18)] = 371,
  [SMALL_STATE(19)] = 388,
  [SMALL_STATE(20)] = 405,
  [SMALL_STATE(21)] = 418,
  [SMALL_STATE(22)] = 435,
  [SMALL_STATE(23)] = 451,
  [SMALL_STATE(24)] = 467,
  [SMALL_STATE(25)] = 483,
  [SMALL_STATE(26)] = 499,
  [SMALL_STATE(27)] = 513,
  [SMALL_STATE(28)] = 529,
  [SMALL_STATE(29)] = 545,
  [SMALL_STATE(30)] = 561,
  [SMALL_STATE(31)] = 577,
  [SMALL_STATE(32)] = 588,
  [SMALL_STATE(33)] = 601,
  [SMALL_STATE(34)] = 610,
  [SMALL_STATE(35)] = 623,
  [SMALL_STATE(36)] = 634,
  [SMALL_STATE(37)] = 647,
  [SMALL_STATE(38)] = 656,
  [SMALL_STATE(39)] = 667,
  [SMALL_STATE(40)] = 680,
  [SMALL_STATE(41)] = 691,
  [SMALL_STATE(42)] = 700,
  [SMALL_STATE(43)] = 709,
  [SMALL_STATE(44)] = 722,
  [SMALL_STATE(45)] = 730,
  [SMALL_STATE(46)] = 738,
  [SMALL_STATE(47)] = 748,
  [SMALL_STATE(48)] = 758,
  [SMALL_STATE(49)] = 766,
  [SMALL_STATE(50)] = 774,
  [SMALL_STATE(51)] = 784,
  [SMALL_STATE(52)] = 794,
  [SMALL_STATE(53)] = 802,
  [SMALL_STATE(54)] = 812,
  [SMALL_STATE(55)] = 820,
  [SMALL_STATE(56)] = 828,
  [SMALL_STATE(57)] = 836,
  [SMALL_STATE(58)] = 846,
  [SMALL_STATE(59)] = 854,
  [SMALL_STATE(60)] = 862,
  [SMALL_STATE(61)] = 872,
  [SMALL_STATE(62)] = 880,
  [SMALL_STATE(63)] = 888,
  [SMALL_STATE(64)] = 895,
  [SMALL_STATE(65)] = 902,
  [SMALL_STATE(66)] = 909,
  [SMALL_STATE(67)] = 916,
  [SMALL_STATE(68)] = 923,
  [SMALL_STATE(69)] = 930,
  [SMALL_STATE(70)] = 937,
  [SMALL_STATE(71)] = 944,
  [SMALL_STATE(72)] = 951,
  [SMALL_STATE(73)] = 958,
  [SMALL_STATE(74)] = 965,
  [SMALL_STATE(75)] = 972,
  [SMALL_STATE(76)] = 979,
  [SMALL_STATE(77)] = 986,
  [SMALL_STATE(78)] = 993,
  [SMALL_STATE(79)] = 1000,
  [SMALL_STATE(80)] = 1007,
  [SMALL_STATE(81)] = 1014,
  [SMALL_STATE(82)] = 1021,
  [SMALL_STATE(83)] = 1028,
  [SMALL_STATE(84)] = 1035,
  [SMALL_STATE(85)] = 1042,
  [SMALL_STATE(86)] = 1049,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_call, 1, 0, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_call, 2, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_call_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_call_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 2, 0, 0), SHIFT_REPEAT(17),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 2, 0, 0), SHIFT_REPEAT(25),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block, 4, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_julia_block_repeat2, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 7),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_if_clause, 3, 0, 3),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_if_clause, 3, 0, 3),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_julia_block, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_julia_block, 3, 0, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_splat_operator, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_julia_block, 3, 0, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_assignment, 3, 0, 5),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 6),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_julia_block, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_property_assignment, 5, 0, 8),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 5, 0, 9),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 3),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 4, 0, 4),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_clause, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 3),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 3),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_definition, 6, 0, 1),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 5, 0, 4),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snippet_definition, 5, 0, 1),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
  },
  [3] = {
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_efus_external_scanner_create(void);
void tree_sitter_efus_external_scanner_destroy(void *);
bool tree_sitter_efus_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_efus_external_scanner_serialize(void *, char *);
void tree_sitter_efus_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_efus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_efus_external_scanner_create,
      tree_sitter_efus_external_scanner_destroy,
      tree_sitter_efus_external_scanner_scan,
      tree_sitter_efus_external_scanner_serialize,
      tree_sitter_efus_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "efus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
